export const learningQueryKeys = {
  all: ["learning"] as const,
  dashboard: ["learning", "dashboard"] as const,
  goals: ["learning", "goals"] as const,
  goalProgress: (id: string) => ["learning", "goals", id, "progress"] as const,
  schedules: ["learning", "study-schedules"] as const,
  sessions: ["learning", "study-sessions"] as const,
  assessments: ["learning", "assessments"] as const,
  bottlenecks: ["learning", "bottlenecks"] as const,
  milestones: ["learning", "milestones"] as const,
  weeklyReviews: ["learning", "weekly-reviews"] as const,
  roadmaps: ["learning", "roadmaps"] as const,
  skills: ["learning", "skills"] as const,
  dueCards: ["learning", "due-cards"] as const,
  reading: ["learning", "reading"] as const,
};
