/** Proposed frontend contract; implement these routes in the backend repository. */
export const API_CONTRACT = [
  {
    domain: "projects",
    method: "GET",
    path: "/projects",
    function: "getProjects",
    response: "PaginatedResponse<Project>",
    query: "{ page: 1, per_page: 100, ...pagination }",
  },
  {
    domain: "projects",
    method: "GET",
    path: "/projects/:id",
    function: "getProject",
    response: "Project | null",
  },
  {
    domain: "projects",
    method: "GET",
    path: "/projects/sprints",
    function: "getSprints",
    response: "Sprint[]",
    query: "{ project_id: projectId }",
  },
  {
    domain: "projects",
    method: "GET",
    path: "/projects/tasks",
    function: "getTasks",
    response: "Task[]",
    query:
      "{ sprint_id: filters.sprintId, project_id: filters.projectId, status: filters.status }",
  },
  {
    domain: "projects",
    method: "GET",
    path: "/projects/milestones",
    function: "getMilestones",
    response: "Milestone[]",
    query: "{ project_id: projectId }",
  },
  {
    domain: "projects",
    method: "POST",
    path: "/projects",
    function: "createProject",
    response: "Project",
    input: "CreateProjectInput",
  },
  {
    domain: "projects",
    method: "PATCH",
    path: "/projects/:id",
    function: "updateProject",
    response: "Project",
    input: "UpdateProjectInput",
  },
  {
    domain: "projects",
    method: "DELETE",
    path: "/projects/:id",
    function: "deleteProject",
    response: "204 (no body)",
  },
  {
    domain: "projects",
    method: "POST",
    path: "/projects/sprints",
    function: "createSprint",
    response: "Sprint",
    input: "CreateSprintInput",
  },
  {
    domain: "projects",
    method: "PATCH",
    path: "/projects/sprints/:id",
    function: "updateSprint",
    response: "Sprint",
    input: "UpdateSprintInput",
  },
  {
    domain: "projects",
    method: "DELETE",
    path: "/projects/sprints/:id",
    function: "deleteSprint",
    response: "204 (no body)",
  },
  {
    domain: "projects",
    method: "POST",
    path: "/projects/tasks",
    function: "createTask",
    response: "Task",
    input: "CreateTaskInput",
  },
  {
    domain: "projects",
    method: "PATCH",
    path: "/projects/tasks/:id",
    function: "updateTask",
    response: "Task",
    input: "UpdateTaskInput",
  },
  {
    domain: "projects",
    method: "DELETE",
    path: "/projects/tasks/:id",
    function: "deleteTask",
    response: "204 (no body)",
  },
  {
    domain: "projects",
    method: "POST",
    path: "/projects/milestones",
    function: "createMilestone",
    response: "Milestone",
    input: "CreateMilestoneInput",
  },
  {
    domain: "projects",
    method: "PATCH",
    path: "/projects/milestones/:id",
    function: "updateMilestone",
    response: "Milestone",
    input: "UpdateMilestoneInput",
  },
  {
    domain: "projects",
    method: "DELETE",
    path: "/projects/milestones/:id",
    function: "deleteMilestone",
    response: "204 (no body)",
  },
  {
    domain: "infrastructure",
    method: "GET",
    path: "/infrastructure/nodes",
    function: "getNodes",
    response: "InfraNode[]",
  },
  {
    domain: "infrastructure",
    method: "GET",
    path: "/infrastructure/nodes/:nodeId/metrics",
    function: "getNodeMetrics",
    response: "SystemMetric[]",
    query: "{ hours }",
  },
  {
    domain: "infrastructure",
    method: "GET",
    path: "/infrastructure/nodes/:nodeId/metrics/latest",
    function: "getLatestMetric",
    response: "SystemMetric | null",
  },
  {
    domain: "infrastructure",
    method: "GET",
    path: "/infrastructure/git",
    function: "getGitActivity",
    response: "GitActivity[]",
  },
  {
    domain: "infrastructure",
    method: "POST",
    path: "/infrastructure/nodes",
    function: "createNode",
    response: "InfraNode",
    input: "CreateNodeInput",
  },
  {
    domain: "infrastructure",
    method: "PATCH",
    path: "/infrastructure/nodes/:id",
    function: "updateNode",
    response: "InfraNode",
    input: "UpdateNodeInput",
  },
  {
    domain: "infrastructure",
    method: "DELETE",
    path: "/infrastructure/nodes/:id",
    function: "deleteNode",
    response: "204 (no body)",
  },
  {
    domain: "health",
    method: "GET",
    path: "/health/training-plans",
    function: "getTrainingPlans",
    response: "TrainingPlan[]",
  },
  {
    domain: "health",
    method: "GET",
    path: "/health/training-plans/:id",
    function: "getTrainingPlan",
    response: "TrainingPlan | null",
  },
  {
    domain: "health",
    method: "GET",
    path: "/health/workouts",
    function: "getWorkoutSessions",
    response: "WorkoutSession[]",
    query: "{ days }",
  },
  {
    domain: "health",
    method: "GET",
    path: "/health/metrics",
    function: "getHealthMetrics",
    response: "HealthMetric[]",
    query: "{ days }",
  },
  {
    domain: "health",
    method: "GET",
    path: "/health/metrics/latest",
    function: "getLatestHealthMetric",
    response: "HealthMetric | null",
  },
  {
    domain: "health",
    method: "POST",
    path: "/health/training-plans",
    function: "createTrainingPlan",
    response: "TrainingPlan",
    input: "CreateTrainingPlanInput",
  },
  {
    domain: "health",
    method: "PATCH",
    path: "/health/training-plans/:id",
    function: "updateTrainingPlan",
    response: "TrainingPlan",
    input: "UpdateTrainingPlanInput",
  },
  {
    domain: "health",
    method: "DELETE",
    path: "/health/training-plans/:id",
    function: "deleteTrainingPlan",
    response: "204 (no body)",
  },
  {
    domain: "health",
    method: "POST",
    path: "/health/workouts",
    function: "createWorkoutSession",
    response: "WorkoutSession",
    input: "CreateWorkoutSessionInput",
  },
  {
    domain: "health",
    method: "PATCH",
    path: "/health/workouts/:id",
    function: "updateWorkoutSession",
    response: "WorkoutSession",
    input: "UpdateWorkoutSessionInput",
  },
  {
    domain: "health",
    method: "DELETE",
    path: "/health/workouts/:id",
    function: "deleteWorkoutSession",
    response: "204 (no body)",
  },
  {
    domain: "health",
    method: "POST",
    path: "/health/metrics",
    function: "createHealthMetric",
    response: "HealthMetric",
    input: "CreateHealthMetricInput",
  },
  {
    domain: "health",
    method: "PATCH",
    path: "/health/metrics/:id",
    function: "updateHealthMetric",
    response: "HealthMetric",
    input: "UpdateHealthMetricInput",
  },
  {
    domain: "health",
    method: "DELETE",
    path: "/health/metrics/:id",
    function: "deleteHealthMetric",
    response: "204 (no body)",
  },
  {
    domain: "finances",
    method: "GET",
    path: "/finances/budget-categories",
    function: "getBudgetCategories",
    response: "BudgetCategory[]",
  },
  {
    domain: "finances",
    method: "GET",
    path: "/finances/transactions",
    function: "getTransactions",
    response: "Transaction[]",
  },
  {
    domain: "finances",
    method: "GET",
    path: "/finances/trades",
    function: "getTrades",
    response: "TradeEntry[]",
  },
  {
    domain: "finances",
    method: "GET",
    path: "/finances/net-worth",
    function: "getNetWorthHistory",
    response: "NetWorthSnapshot[]",
    query: "{ months }",
  },
  {
    domain: "finances",
    method: "GET",
    path: "/finances/bills",
    function: "getBills",
    response: "Bill[]",
  },
  {
    domain: "finances",
    method: "POST",
    path: "/finances/transactions",
    function: "createTransaction",
    response: "Transaction",
    input: "CreateTransactionInput",
  },
  {
    domain: "finances",
    method: "PATCH",
    path: "/finances/transactions/:id",
    function: "updateTransaction",
    response: "Transaction",
    input: "UpdateTransactionInput",
  },
  {
    domain: "finances",
    method: "DELETE",
    path: "/finances/transactions/:id",
    function: "deleteTransaction",
    response: "204 (no body)",
  },
  {
    domain: "finances",
    method: "POST",
    path: "/finances/budget-categories",
    function: "createBudgetCategory",
    response: "BudgetCategory",
    input: "CreateBudgetCategoryInput",
  },
  {
    domain: "finances",
    method: "PATCH",
    path: "/finances/budget-categories/:id",
    function: "updateBudgetCategory",
    response: "BudgetCategory",
    input: "UpdateBudgetCategoryInput",
  },
  {
    domain: "finances",
    method: "DELETE",
    path: "/finances/budget-categories/:id",
    function: "deleteBudgetCategory",
    response: "204 (no body)",
  },
  {
    domain: "finances",
    method: "POST",
    path: "/finances/bills",
    function: "createBill",
    response: "Bill",
    input: "CreateBillInput",
  },
  {
    domain: "finances",
    method: "PATCH",
    path: "/finances/bills/:id",
    function: "updateBill",
    response: "Bill",
    input: "UpdateBillInput",
  },
  {
    domain: "finances",
    method: "DELETE",
    path: "/finances/bills/:id",
    function: "deleteBill",
    response: "204 (no body)",
  },
  {
    domain: "learning",
    method: "GET",
    path: "/learning/roadmaps",
    function: "getRoadmaps",
    response: "LearningRoadmap[]",
  },
  {
    domain: "learning",
    method: "GET",
    path: "/learning/skills",
    function: "getSkills",
    response: "SkillNode[]",
    query: "{ roadmap_id: roadmapId }",
  },
  {
    domain: "learning",
    method: "GET",
    path: "/learning/sr-cards",
    function: "getDueCards",
    response: "SpacedRepetitionCard[]",
    query: "{ due: true }",
  },
  {
    domain: "learning",
    method: "GET",
    path: "/learning/sr-cards",
    function: "getAllCards",
    response: "SpacedRepetitionCard[]",
  },
  {
    domain: "learning",
    method: "GET",
    path: "/learning/reading",
    function: "getReadingList",
    response: "ReadingEntry[]",
  },
  {
    domain: "learning",
    method: "POST",
    path: "/learning/roadmaps",
    function: "createRoadmap",
    response: "LearningRoadmap",
    input: "CreateRoadmapInput",
  },
  {
    domain: "learning",
    method: "PATCH",
    path: "/learning/roadmaps/:id",
    function: "updateRoadmap",
    response: "LearningRoadmap",
    input: "UpdateRoadmapInput",
  },
  {
    domain: "learning",
    method: "DELETE",
    path: "/learning/roadmaps/:id",
    function: "deleteRoadmap",
    response: "204 (no body)",
  },
  {
    domain: "learning",
    method: "POST",
    path: "/learning/reading",
    function: "createReadingEntry",
    response: "ReadingEntry",
    input: "CreateReadingEntryInput",
  },
  {
    domain: "learning",
    method: "PATCH",
    path: "/learning/reading/:id",
    function: "updateReadingEntry",
    response: "ReadingEntry",
    input: "UpdateReadingEntryInput",
  },
  {
    domain: "learning",
    method: "DELETE",
    path: "/learning/reading/:id",
    function: "deleteReadingEntry",
    response: "204 (no body)",
  },
  {
    domain: "work",
    method: "GET",
    path: "/work/career-milestones",
    function: "getCareerMilestones",
    response: "CareerMilestone[]",
  },
  {
    domain: "work",
    method: "GET",
    path: "/work/certifications",
    function: "getCertifications",
    response: "Certification[]",
  },
  {
    domain: "work",
    method: "GET",
    path: "/work/deadlines",
    function: "getDeadlines",
    response: "WorkDeadline[]",
  },
  {
    domain: "work",
    method: "GET",
    path: "/work/compliance",
    function: "getComplianceItems",
    response: "ComplianceItem[]",
  },
  {
    domain: "work",
    method: "POST",
    path: "/work/deadlines",
    function: "createDeadline",
    response: "WorkDeadline",
    input: "CreateDeadlineInput",
  },
  {
    domain: "work",
    method: "PATCH",
    path: "/work/deadlines/:id",
    function: "updateDeadline",
    response: "WorkDeadline",
    input: "UpdateDeadlineInput",
  },
  {
    domain: "work",
    method: "DELETE",
    path: "/work/deadlines/:id",
    function: "deleteDeadline",
    response: "204 (no body)",
  },
  {
    domain: "work",
    method: "POST",
    path: "/work/certifications",
    function: "createCertification",
    response: "Certification",
    input: "CreateCertificationInput",
  },
  {
    domain: "work",
    method: "PATCH",
    path: "/work/certifications/:id",
    function: "updateCertification",
    response: "Certification",
    input: "UpdateCertificationInput",
  },
  {
    domain: "work",
    method: "DELETE",
    path: "/work/certifications/:id",
    function: "deleteCertification",
    response: "204 (no body)",
  },
  {
    domain: "social",
    method: "GET",
    path: "/social/contacts",
    function: "getContacts",
    response: "Contact[]",
  },
  {
    domain: "social",
    method: "GET",
    path: "/social/contacts/:id",
    function: "getContact",
    response: "Contact | null",
  },
  {
    domain: "social",
    method: "GET",
    path: "/social/networking-goals",
    function: "getNetworkingGoals",
    response: "NetworkingGoal[]",
  },
  {
    domain: "social",
    method: "GET",
    path: "/social/follow-ups",
    function: "getFollowUps",
    response: "FollowUpPrompt[]",
    query: "{ completed }",
  },
  {
    domain: "social",
    method: "POST",
    path: "/social/contacts",
    function: "createContact",
    response: "Contact",
    input: "CreateContactInput",
  },
  {
    domain: "social",
    method: "PATCH",
    path: "/social/contacts/:id",
    function: "updateContact",
    response: "Contact",
    input: "UpdateContactInput",
  },
  {
    domain: "social",
    method: "DELETE",
    path: "/social/contacts/:id",
    function: "deleteContact",
    response: "204 (no body)",
  },
  {
    domain: "appearance",
    method: "GET",
    path: "/appearance/wardrobe",
    function: "getWardrobeItems",
    response: "WardrobeItem[]",
  },
  {
    domain: "appearance",
    method: "GET",
    path: "/appearance/outfits",
    function: "getOutfitLogs",
    response: "OutfitLog[]",
    query: "{ limit }",
  },
  {
    domain: "appearance",
    method: "GET",
    path: "/appearance/grooming",
    function: "getGroomingRoutines",
    response: "GroomingRoutine[]",
  },
  {
    domain: "appearance",
    method: "GET",
    path: "/appearance/spend",
    function: "getAppearanceSpend",
    response: "AppearanceSpend[]",
  },
  {
    domain: "appearance",
    method: "POST",
    path: "/appearance/wardrobe",
    function: "createWardrobeItem",
    response: "WardrobeItem",
    input: "CreateWardrobeItemInput",
  },
  {
    domain: "appearance",
    method: "PATCH",
    path: "/appearance/wardrobe/:id",
    function: "updateWardrobeItem",
    response: "WardrobeItem",
    input: "UpdateWardrobeItemInput",
  },
  {
    domain: "appearance",
    method: "DELETE",
    path: "/appearance/wardrobe/:id",
    function: "deleteWardrobeItem",
    response: "204 (no body)",
  },
  {
    domain: "appearance",
    method: "POST",
    path: "/appearance/outfits",
    function: "createOutfitLog",
    response: "OutfitLog",
    input: "CreateOutfitLogInput",
  },
  {
    domain: "appearance",
    method: "PATCH",
    path: "/appearance/outfits/:id",
    function: "updateOutfitLog",
    response: "OutfitLog",
    input: "UpdateOutfitLogInput",
  },
  {
    domain: "appearance",
    method: "DELETE",
    path: "/appearance/outfits/:id",
    function: "deleteOutfitLog",
    response: "204 (no body)",
  },
  {
    domain: "logistics",
    method: "GET",
    path: "/logistics/trips",
    function: "getTrips",
    response: "Trip[]",
  },
  {
    domain: "logistics",
    method: "GET",
    path: "/logistics/checklists",
    function: "getChecklists",
    response: "ChecklistTemplate[]",
  },
  {
    domain: "logistics",
    method: "GET",
    path: "/logistics/documents",
    function: "getDocuments",
    response: "DocumentRecord[]",
  },
  {
    domain: "logistics",
    method: "GET",
    path: "/logistics/events",
    function: "getLogisticsEvents",
    response: "LogisticsEvent[]",
  },
  {
    domain: "logistics",
    method: "POST",
    path: "/logistics/trips",
    function: "createTrip",
    response: "Trip",
    input: "CreateTripInput",
  },
  {
    domain: "logistics",
    method: "PATCH",
    path: "/logistics/trips/:id",
    function: "updateTrip",
    response: "Trip",
    input: "UpdateTripInput",
  },
  {
    domain: "logistics",
    method: "DELETE",
    path: "/logistics/trips/:id",
    function: "deleteTrip",
    response: "204 (no body)",
  },
  {
    domain: "logistics",
    method: "POST",
    path: "/logistics/documents",
    function: "createDocument",
    response: "DocumentRecord",
    input: "CreateDocumentInput",
  },
  {
    domain: "logistics",
    method: "PATCH",
    path: "/logistics/documents/:id",
    function: "updateDocument",
    response: "DocumentRecord",
    input: "UpdateDocumentInput",
  },
  {
    domain: "logistics",
    method: "DELETE",
    path: "/logistics/documents/:id",
    function: "deleteDocument",
    response: "204 (no body)",
  },
  {
    domain: "logistics",
    method: "POST",
    path: "/logistics/events",
    function: "createLogisticsEvent",
    response: "LogisticsEvent",
    input: "CreateLogisticsEventInput",
  },
  {
    domain: "logistics",
    method: "PATCH",
    path: "/logistics/events/:id",
    function: "updateLogisticsEvent",
    response: "LogisticsEvent",
    input: "UpdateLogisticsEventInput",
  },
  {
    domain: "logistics",
    method: "DELETE",
    path: "/logistics/events/:id",
    function: "deleteLogisticsEvent",
    response: "204 (no body)",
  },
  {
    domain: "learning",
    method: "POST",
    path: "/learning/sr-cards/:id/reviews",
    function: "reviewCard",
    response: "SpacedRepetitionCard",
    input: "id: string, input: { reviewed_at: string }, ",
  },
  {
    domain: "work",
    method: "PATCH",
    path: "/work/compliance/:id",
    function: "updateComplianceItem",
    response: "ComplianceItem",
    input: 'id: string, input: Pick<ComplianceItem, "completed">, ',
  },
  {
    domain: "social",
    method: "PATCH",
    path: "/social/follow-ups/:id",
    function: "updateFollowUp",
    response: "FollowUpPrompt",
    input: 'id: string, input: Pick<FollowUpPrompt, "completed">, ',
  },
  {
    domain: "logistics",
    method: "PATCH",
    path: "/logistics/checklists/:checklist_id/items/:item_id",
    function: "updateChecklistItem",
    response: "ChecklistItem",
    input:
      'checklistId: string, itemId: string, input: Pick<ChecklistItem, "completed">, ',
  },
  {
    domain: "logistics",
    method: "POST",
    path: "/logistics/checklists/:id/reset",
    function: "resetChecklist",
    response: "ChecklistTemplate",
    input: "id: string, ",
  },
  {
    domain: "intelligence",
    method: "GET",
    path: "/intelligence/sleep-vs-commits",
    function: "getSleepVsCommits",
    response: "CorrelationPoint[]",
  },
  {
    domain: "intelligence",
    method: "GET",
    path: "/intelligence/budget-vs-velocity",
    function: "getBudgetVsVelocity",
    response: "CorrelationPoint[]",
  },
  {
    domain: "intelligence",
    method: "GET",
    path: "/intelligence/hrv-vs-rpe",
    function: "getHrvVsRpe",
    response: "CorrelationPoint[]",
  },
  {
    domain: "intelligence",
    method: "GET",
    path: "/intelligence/net-worth",
    function: "getNetWorthTrend",
    response: "CorrelationPoint[]",
  },
  {
    domain: "intelligence",
    method: "GET",
    path: "/intelligence/sleep-trend",
    function: "getSleepTrend",
    response: "(number | null)[]",
  },
  {
    domain: "intelligence",
    method: "GET",
    path: "/intelligence/commits-trend",
    function: "getCommitsTrend",
    response: "(number | null)[]",
  },
  {
    domain: "notifications",
    method: "GET",
    path: "/notifications",
    function: "getNotifications",
    response: "Notification[]",
  },
  {
    domain: "notifications",
    method: "PATCH",
    path: "/notifications/:id",
    function: "markNotificationRead / dismissNotification",
    response: "Notification",
    input: '{ status: "read" | "dismissed" }',
  },
  {
    domain: "notifications",
    method: "POST",
    path: "/notifications/read-all",
    function: "markAllRead",
    response: "204 (no body)",
    input: "{}",
  },
  {
    domain: "triggers",
    method: "GET",
    path: "/triggers/rules",
    function: "getTriggerRules",
    response: "TriggerRule[]",
  },
  {
    domain: "triggers",
    method: "POST",
    path: "/triggers/rules",
    function: "createTriggerRule",
    response: "TriggerRule",
    input: "CreateTriggerRuleInput",
  },
  {
    domain: "triggers",
    method: "PATCH",
    path: "/triggers/rules/:id",
    function: "updateTriggerRule",
    response: "TriggerRule",
    input: "UpdateTriggerRuleInput",
  },
  {
    domain: "triggers",
    method: "DELETE",
    path: "/triggers/rules/:id",
    function: "deleteTriggerRule",
    response: "204 (no body)",
  },
  {
    domain: "triggers",
    method: "GET",
    path: "/triggers/log",
    function: "getTriggerLog",
    response: "TriggerLogEntry[]",
  },
  {
    domain: "triggers",
    method: "PATCH",
    path: "/triggers/log/:id",
    function: "resolveTriggerLogEntry",
    response: "TriggerLogEntry",
    input: "{ resolved: true }",
  },
] as const;
